name: AdminToybox
main: no.runsafe.toybox.Plugin
version: 1.0.@BUILD@
author: mortenn
description: A collection of toys for admins
commands:
  bazooka:
    description: Launches and detonates some entity
  bomb:
    description: Fires a wither bomb
  dismount:
    description: Ejects you from your vehicle
  dynamite:
    description: Fires a primed TNT
  fireball:
    description: Fires a fireball
  firework:
    description: Sets off a firework
  lightning:
    description: Strikes lightning on a player or coordinate
  mount:
    description: Mounts you on a player or entity
  spawnmob:
    description: Spawns a mob
  spawnhorse:
    description: Spawns a horse
  ride:
    description: Spawns a mob and mounts you to it
  createhead:
    description: Creates a players head
    aliases: [head]
  mode:
    description: Allows you to change the players game mode
  carepackage:
    description: Drops a care-package from the sky
  mobdrop:
    description: Drops a block of mobs from the sky
  nuke:
    description: Drops a nuke with the provided parameters.
  spawngodmob:
    description: Spawns a god mob
  enchant:
    description: Enchants an item.
  renameitem:
    description: Renames an item in your hand.
  give:
    description: Gives a player the items specified.
    aliases: [item, i, give]
  kill:
    description: Kills a specific player or yourself
  buff:
    description: Apply a buff to a player with the desired duration and amplification
    aliases: [effect, potion]
  colour:
    description: Colours a leather armour item with the supplied hex code
    aliases: [dye]
  author:
    description: Changes the author of a book
  playsound:
    description: Plays a sound
    aliases: [ps]
  lock:
    description: Enables locking and unlocking of objects.