name: AdminToybox
main: no.runsafe.toybox.Plugin
version: 1.0.@BUILD@
author: mortenn
description: A collection of toys for admins
commands:
  bazooka:
    description: Launches and detonates some entity
  bomb:
    description: Fires a wither bomb
  dismount:
    description: Ejects you from your vehicle
  dynamite:
    description: Fires a primed TNT
  fireball:
    description: Fires a fireball
  firework:
    description: Sets off a firework
  lightning:
    description: Strikes lightning on a player or coordinate
  mount:
    description: Mounts you on a player or entity
  spawnmob:
    description: Spawns a mob
  ride:
    description: Spawns a mob and mounts you to it
  createhead:
    description: Creates a players head
  mode:
    description: Allows you to change the players game mode
  carepackage:
    description: Drops a care-package from the sky
  mobdrop:
    description: Drops a block of mobs from the sky
  nuke:
    description: Drops a nuke with the provided parameters.
  spawngodmob:
    description: Spawns a god mob
  enchant:
    description: Enchants an item.
  renameitem:
    description: Renames an item in your hand.