name: AdminToybox
main: no.runsafe.toybox.Plugin
version: 1.0.@BUILD@
authors: []
depend: []
description:
commands:
  bomb:
    description: Fires a wither bomb
  dynamite:
    description: Fires a primed TNT
  fireball:
    description: Fires a fireball
  firework:
    description: Sets off a firework
  lightning:
    description: Strikes lightning on a player or coordinate
  spawnmob:
    description: Spawns a mob
  ride:
    description: Spawns a mob and mounts you to it
